# https://docs.travis-ci.com/user/customizing-the-build/
# https://docs.travis-ci.com/user/job-lifecycle/#the-job-lifecycle
# https://docs.travis-ci.com/user/languages/objective-c/

branches:
  only:
  - master
  - /^hotfix.*$/
  - /^release.*$/
  - /^feature.*$/

git:
  depth: 3
  submodules: false

language: objective-c # fine for Swift as well

osx_image:
  - xcode10.1

before_install:
 - bundle install --jobs=3 --retry=3 --deployment --path .vendor/bundle

install:
  - bundle exec pod repo update

before_script:
  # cd ./.setup && swift run && cd ./.. # RUN this manually!
  - swift --version

script:
  - bundle exec fastlane lintThoroughly
