# https://github.com/lyptt/struct/wiki/Spec-format:-v2.0

version: 2.1.0
configurations:
  debug:
    overrides:
      WATCHOS_DEPLOYMENT_TARGET: '3.0'
      CURRENT_PROJECT_VERSION: '0'
      CLANG_WARN_COMMA: 'YES'
      SWIFT_OPTIMIZATION_LEVEL: '-Onone'
      CLANG_WARN_STRICT_PROTOTYPES: 'YES'
      IPHONEOS_DEPLOYMENT_TARGET: '9.0'
      CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: 'YES'
      SWIFT_VERSION: '4.2'
      MACOSX_DEPLOYMENT_TARGET: '10.11'
      CLANG_WARN_NON_LITERAL_NULL_CONVERSION: 'YES'
      CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: 'YES'
      CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING: 'YES'
      PRODUCT_NAME: 'XCEPipeline'
      CLANG_WARN_OBJC_LITERAL_CONVERSION: 'YES'
      VERSIONING_SYSTEM: 'apple-generic'
      TVOS_DEPLOYMENT_TARGET: '9.0'
      CLANG_WARN_RANGE_LOOP_ANALYSIS: 'YES'
  release:
    overrides:
      WATCHOS_DEPLOYMENT_TARGET: '3.0'
      CURRENT_PROJECT_VERSION: '0'
      CLANG_WARN_COMMA: 'YES'
      CLANG_WARN_STRICT_PROTOTYPES: 'YES'
      IPHONEOS_DEPLOYMENT_TARGET: '9.0'
      CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: 'YES'
      SWIFT_VERSION: '4.2'
      MACOSX_DEPLOYMENT_TARGET: '10.11'
      CLANG_WARN_NON_LITERAL_NULL_CONVERSION: 'YES'
      CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: 'YES'
      CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING: 'YES'
      PRODUCT_NAME: 'XCEPipeline'
      CLANG_WARN_OBJC_LITERAL_CONVERSION: 'YES'
      VERSIONING_SYSTEM: 'apple-generic'
      TVOS_DEPLOYMENT_TARGET: '9.0'
      CLANG_WARN_RANGE_LOOP_ANALYSIS: 'YES'
targets:
  tvOS-Pipeline:
    platform: tv
    type: ":framework"
    sources:
    - Sources/Pipeline/Common
    - Sources/Pipeline/tvOS
    source_options:
    configurations:
      debug:
        SKIP_INSTALL: "YES"
        PRODUCT_NAME: "$(inherited)"
        CODE_SIGN_IDENTITY: "iPhone Developer"
        SWIFT_VERSION: "$(inherited)"
        TVOS_DEPLOYMENT_TARGET: "9.0"
        DEFINES_MODULE: "YES"
        PRODUCT_BUNDLE_IDENTIFIER: "com.XCEssentials.tvOS-Pipeline"
        MTL_ENABLE_DEBUG_INFO: "INCLUDE_SOURCE"
        INFOPLIST_FILE: "Info/tvOS-Pipeline.plist"
        CODE_SIGN_STYLE: "Automatic"
      release:
        SKIP_INSTALL: "YES"
        PRODUCT_NAME: "$(inherited)"
        CODE_SIGN_IDENTITY: "iPhone Developer"
        SWIFT_VERSION: "$(inherited)"
        TVOS_DEPLOYMENT_TARGET: "9.0"
        DEFINES_MODULE: "YES"
        PRODUCT_BUNDLE_IDENTIFIER: "com.XCEssentials.tvOS-Pipeline"
        MTL_ENABLE_DEBUG_INFO: "YES"
        INFOPLIST_FILE: "Info/tvOS-Pipeline.plist"
        CODE_SIGN_STYLE: "Automatic"
  tvOS-PipelineTests:
    platform: tv
    type: ":bundle.unit-test"
    references:
    - location: tvOS-Pipeline
    sources:
    - Sources/PipelineTests/Common
    - Sources/PipelineTests/tvOS
    source_options:
    configurations:
      debug:
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @loader_path/Frameworks"
        FRAMEWORK_SEARCH_PATHS: "$(inherited) $(BUILT_PRODUCTS_DIR)"
        SWIFT_VERSION: "$(inherited)"
        TVOS_DEPLOYMENT_TARGET: "9.0"
        PRODUCT_BUNDLE_IDENTIFIER: "com.XCEssentials.tvOS-PipelineTests"
        MTL_ENABLE_DEBUG_INFO: "YES"
        INFOPLIST_FILE: "Info/tvOS-PipelineTests.plist"
      release:
        SWIFT_VERSION: "$(inherited)"
        PRODUCT_BUNDLE_IDENTIFIER: "com.XCEssentials.tvOS-PipelineTests"
        INFOPLIST_FILE: "Info/tvOS-PipelineTests.plist"
        FRAMEWORK_SEARCH_PATHS: "$(inherited) $(BUILT_PRODUCTS_DIR)"
        TVOS_DEPLOYMENT_TARGET: "9.0"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @loader_path/Frameworks"
  macOS-Pipeline:
    platform: mac
    type: ":framework"
    sources:
    - Sources/Pipeline/Common
    - Sources/Pipeline/macOS
    source_options:
    configurations:
      debug:
        SKIP_INSTALL: "YES"
        PRODUCT_NAME: "$(inherited)"
        CODE_SIGN_IDENTITY: "Mac Developer"
        SWIFT_VERSION: "$(inherited)"
        SDKROOT: "macosx"
        MACOSX_DEPLOYMENT_TARGET: "10.11"
        DEFINES_MODULE: "YES"
        PRODUCT_BUNDLE_IDENTIFIER: "com.XCEssentials.macOS-Pipeline"
        MTL_ENABLE_DEBUG_INFO: "INCLUDE_SOURCE"
        INFOPLIST_FILE: "Info/macOS-Pipeline.plist"
        CODE_SIGN_STYLE: "Automatic"
      release:
        SKIP_INSTALL: "YES"
        PRODUCT_NAME: "$(inherited)"
        CODE_SIGN_IDENTITY: "Mac Developer"
        SWIFT_VERSION: "$(inherited)"
        SDKROOT: "macosx"
        MACOSX_DEPLOYMENT_TARGET: "10.11"
        DEFINES_MODULE: "YES"
        PRODUCT_BUNDLE_IDENTIFIER: "com.XCEssentials.macOS-Pipeline"
        MTL_ENABLE_DEBUG_INFO: "YES"
        INFOPLIST_FILE: "Info/macOS-Pipeline.plist"
        CODE_SIGN_STYLE: "Automatic"
  macOS-PipelineTests:
    platform: mac
    type: ":bundle.unit-test"
    references:
    - location: macOS-Pipeline
    sources:
    - Sources/PipelineTests/Common
    - Sources/PipelineTests/macOS
    source_options:
    configurations:
      debug:
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @loader_path/Frameworks"
        FRAMEWORK_SEARCH_PATHS: "$(inherited) $(BUILT_PRODUCTS_DIR)"
        SWIFT_VERSION: "$(inherited)"
        MACOSX_DEPLOYMENT_TARGET: "10.11"
        PRODUCT_BUNDLE_IDENTIFIER: "com.XCEssentials.macOS-PipelineTests"
        MTL_ENABLE_DEBUG_INFO: "YES"
        INFOPLIST_FILE: "Info/macOS-PipelineTests.plist"
      release:
        SWIFT_VERSION: "$(inherited)"
        PRODUCT_BUNDLE_IDENTIFIER: "com.XCEssentials.macOS-PipelineTests"
        INFOPLIST_FILE: "Info/macOS-PipelineTests.plist"
        FRAMEWORK_SEARCH_PATHS: "$(inherited) $(BUILT_PRODUCTS_DIR)"
        MACOSX_DEPLOYMENT_TARGET: "10.11"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @loader_path/Frameworks"
  watchOS-Pipeline:
    platform: watch
    type: ":framework"
    sources:
    - Sources/Pipeline/Common
    - Sources/Pipeline/watchOS
    source_options:
    configurations:
      debug:
        SKIP_INSTALL: "YES"
        PRODUCT_NAME: "$(inherited)"
        CODE_SIGN_IDENTITY: "iPhone Developer"
        SWIFT_VERSION: "$(inherited)"
        WATCHOS_DEPLOYMENT_TARGET: "3.0"
        DEFINES_MODULE: "YES"
        PRODUCT_BUNDLE_IDENTIFIER: "com.XCEssentials.watchOS-Pipeline"
        MTL_ENABLE_DEBUG_INFO: "INCLUDE_SOURCE"
        INFOPLIST_FILE: "Info/watchOS-Pipeline.plist"
        CODE_SIGN_STYLE: "Automatic"
      release:
        SKIP_INSTALL: "YES"
        PRODUCT_NAME: "$(inherited)"
        CODE_SIGN_IDENTITY: "iPhone Developer"
        SWIFT_VERSION: "$(inherited)"
        WATCHOS_DEPLOYMENT_TARGET: "3.0"
        DEFINES_MODULE: "YES"
        PRODUCT_BUNDLE_IDENTIFIER: "com.XCEssentials.watchOS-Pipeline"
        MTL_ENABLE_DEBUG_INFO: "YES"
        INFOPLIST_FILE: "Info/watchOS-Pipeline.plist"
        CODE_SIGN_STYLE: "Automatic"
  iOS-Pipeline:
    platform: ios
    type: ":framework"
    sources:
    - Sources/Pipeline/Common
    - Sources/Pipeline/iOS
    source_options:
    configurations:
      debug:
        MTL_ENABLE_DEBUG_INFO: "INCLUDE_SOURCE"
        IPHONEOS_DEPLOYMENT_TARGET: "9.0"
        PRODUCT_NAME: "$(inherited)"
        CODE_SIGN_IDENTITY: "iPhone Developer"
        SKIP_INSTALL: "YES"
        SWIFT_VERSION: "$(inherited)"
        SDKROOT: "iphoneos"
        DEFINES_MODULE: "YES"
        PRODUCT_BUNDLE_IDENTIFIER: "com.XCEssentials.iOS-Pipeline"
        TARGETED_DEVICE_FAMILY: "1,2"
        INFOPLIST_FILE: "Info/iOS-Pipeline.plist"
        CODE_SIGN_STYLE: "Automatic"
      release:
        MTL_ENABLE_DEBUG_INFO: "YES"
        IPHONEOS_DEPLOYMENT_TARGET: "9.0"
        PRODUCT_NAME: "$(inherited)"
        CODE_SIGN_IDENTITY: "iPhone Developer"
        SKIP_INSTALL: "YES"
        SWIFT_VERSION: "$(inherited)"
        SDKROOT: "iphoneos"
        DEFINES_MODULE: "YES"
        PRODUCT_BUNDLE_IDENTIFIER: "com.XCEssentials.iOS-Pipeline"
        TARGETED_DEVICE_FAMILY: "1,2"
        INFOPLIST_FILE: "Info/iOS-Pipeline.plist"
        CODE_SIGN_STYLE: "Automatic"
  iOS-PipelineTests:
    platform: ios
    type: ":bundle.unit-test"
    references:
    - location: iOS-Pipeline
    sources:
    - Sources/PipelineTests/Common
    - Sources/PipelineTests/iOS
    source_options:
    configurations:
      debug:
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @loader_path/Frameworks"
        FRAMEWORK_SEARCH_PATHS: "$(inherited) $(BUILT_PRODUCTS_DIR)"
        IPHONEOS_DEPLOYMENT_TARGET: "9.0"
        SWIFT_VERSION: "$(inherited)"
        PRODUCT_BUNDLE_IDENTIFIER: "com.XCEssentials.iOS-PipelineTests"
        MTL_ENABLE_DEBUG_INFO: "YES"
        INFOPLIST_FILE: "Info/iOS-PipelineTests.plist"
      release:
        SWIFT_VERSION: "$(inherited)"
        PRODUCT_BUNDLE_IDENTIFIER: "com.XCEssentials.iOS-PipelineTests"
        INFOPLIST_FILE: "Info/iOS-PipelineTests.plist"
        FRAMEWORK_SEARCH_PATHS: "$(inherited) $(BUILT_PRODUCTS_DIR)"
        IPHONEOS_DEPLOYMENT_TARGET: "9.0"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @loader_path/Frameworks"
variants:
  $base:
    abstract: true
  Pipeline: